# Simple App on Linux Web App
# Package and deploy a simple web application and deploy it to Azure as Linux web app.

trigger:
- {{{ sourceRepository.branch }}}

variables:
  # Azure Resource Manager connection
  azureSubscription: '{{{ targetResource.serviceConnectionId }}}'

  # Web app name
  webAppName: '{{{ targetResource.resource.name }}}'

  # Working Directory
  workingDirectory: '{{{ workingDirectory }}}'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'

    steps:

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: $(workingDirectory)
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - upload: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      artifact: drop

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    environment: 'development'
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Azure Web App: $(webAppName)'
            inputs:
              azureSubscription: $(azureSubscription)
              appType: webAppLinux
              appName: $(webAppName)
              package: $(Pipeline.Workspace)/drop/$(Build.BuildId).zip
              startupCommand: '' # Provide an optional startup command that will be run as part of container startup. For Node, it is the PM2 configuration file or your script file; For .Net Core it is the compiled DLL name as dotnet <myapp>.dll. Learn more at https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-faq#built-in-images
