# Python Function App to Linux on Azure
# Build a Python function app and deploy it to Azure as a Linux function app.
# Add steps that analyze code, save build artifacts, deploy, and more:

on:
  push:
    branches:
      - {{{ sourceRepository.branch }}}

name: Build and deploy Python Function app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # checkout the repo
    - uses: actions/checkout@master
    
    # Setup python
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    # Install dependencies
    - name: 'Run pip'
      shell: bash
      working-directory: {{{ workingDirectory }}}
      run: |
        python -m pip install --upgrade pip
        python -m venv --copies worker_venv
        source worker_venv/bin/activate
        pip install -r {{{repositoryAnalysisApplicationSettings.settings.pythonRequirementsFilePath}}}

    # upload artificats
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: webapp
        path: |
          .
          !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    
    # Download artifacts
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: webapp
        path: . 
  
    # Azure login
    - uses: azure/login@v1
      with:
        creds: {{=<% %>=}}${{ secrets.<% targetResource.serviceConnectionId %> }}<%={{ }}=%>

    # deploy function
    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: {{{ targetResource.resource.name }}}
        package: {{{ workingDirectory }}}
        scm-do-build-during-deployment: true
        enable-oryx-build: true

    # Azure logout
    - name: logout
      run: |
        az logout